title: BioCypher adapter for protein metabolite interactions

# Nodes

small molecule:
  represented_as: node
  preferred_id: HMDB
  label_in_input: hmdb_metabolite
  properties:
   name: str
   kegg_id: KEGG
   chebi_id: int
   pubchem_compound_id: int
   cellular_locations: str[]
   biospecimen_locations: str[]
   tissue_locations: str[]
   pathways: str[]
   diseases: str[]
   kingdom: str
   class: str
   sub_class: str
   molecular_framework: str
  #  protein_accession: str{}

protein:
  represented_as: node
  preferred_id: uniprot
  label_in_input: protein
  properties:
    length: int
    mass: int
    protein_names: str[]
    gene_names: str[]
    proteome: str[]
    organism_id: int
    ec: str[]
    virus_hosts: int[] 
    symbol : str
    subcellular_location: str[]
    cc_disease: int[]
    receptor_type: str

# Edges

# enzymatic interaction:
#   is_a: chemical to gene association

# enzymatic production:
#   is_a: enzymatic interaction


hmdb production degradation:
  is_a: association
  represented_as: edge
  source: small molecule
  target: protein
  label_in_input: PD_hmdb
  properties:
    # met_name: str
    direction: str
    status: str
    reaction_id: int
    subsystem: str
    # external_links: str


recon production degradation:
  is_a: association
  represented_as: edge
  source: small molecule
  target: protein
  label_in_input: PD_recon
  properties:
    status: str
    direction: str
    subsystem: str
    transport: str
    transport_direction: str
    rev: str

hmr production degradation:
  is_a: association
  represented_as: edge
  source: small molecule
  target: protein
  label_in_input: PD_hmr
  properties:
    status: str
    direction: str
    subsystem: str
    transport: str
    transport_direction: str
    rev: str

rhea production degradation:
  is_a: association
  represented_as: edge
  source: small molecule
  target: protein
  label_in_input: PD_rhea
  properties:
    status: str
    direction: str
    # subsystem: str
    # transport: str
    # transport_direction: str
    # rev: str


stitch metabolite receptor:
  is_a: association
  represented_as: edge
  source: small molecule
  target: protein
  label_in_input: MR
  properties:
      mode: str
      database: int
      experiment: int
      prediction: int
      textmining: int
      combined_score: int

cellphone metabolite receptor:
  is_a: association
  represented_as: edge
  source: small molecule
  target: protein
  label_in_input: CP
  properties:
      mode: str

neuronchat metabolite receptor:
  is_a: association
  represented_as: edge
  source: small molecule
  target: protein
  label_in_input: NC
  properties:
      mode: str

cellinker metabolite receptor:
  is_a: association
  represented_as: edge
  source: small molecule
  target: protein
  label_in_input: CL
  properties:
      mode: str

scconnect metabolite receptor:
  is_a: association
  represented_as: edge
  source: small molecule
  target: protein
  label_in_input: SCC
  properties:
      mode: str


