title: BioCypher adapter for HMDB interactions

# Nodes

small molecule:
  represented_as: node
  preferred_id: HMDB
  label_in_input: metabolite
  properties:
   name: str
   keggID: str
   chebiID: str
   pubchemID: int
   proteins: str
   pathways: str

protein:
  represented_as: node
  preferred_id: uniprot
  label_in_input: protein
  properties:
    symbol: hgnc.symbol
    pathways: str
    metabolites: str
    hmdbp_id: str


# Edges

small molecule to gene association:
  is_a: chemical to gene association
  represented_as: edge
  source: small molecule
  target: gene
  label_in_input: metabolite_to_protein
  properties:
    met_name: str
    type: str
    status: str
    reaction_id: str