title: BioCypher adapter for HMDB interactions

# Nodes

small molecule:
  represented_as: node
  preferred_id: HMDB
  label_in_input: hmdb_metabolite
  properties:
   name: str
   kegg_id: KEGG
   chebi_id: int
   pubchem_compound_id: int
   protein_accession: str{}
   pathways: str{}

protein:
  represented_as: node
  preferred_id: uniprot
  label_in_input: protein
  properties:
    secondary_ids: str[]
    length: int
    mass: int
    protein_names: str[]
    proteome: str[]
    organism_id: int
    ec: str[]
    virus_hosts: int[] 

# Edges

production degradation metabolite protein interaction:
  is_a: chemical to gene association
  represented_as: edge
  source: small molecule
  target: protein
  label_in_input: PD
  properties:
    met_name: str
    type: str
    status: str
    reaction_id: int
    external_links: str


recon production degradation metabolite protein interaction:
  is_a: chemical to gene association
  represented_as: edge
  source: small molecule
  target: protein
  label_in_input: PD
  properties:
    status: str
    direction: str


communication metabolite protein interaction:
  is_a: chemical to gene association
  represented_as: edge
  source: small molecule
  target: protein
  label_in_input: MR
  properties:
      mode: str
      database: int
      experiment: int
      prediction: int
      textmining: int
      combined_score: int

